[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
rightshift = overload(alt,?)
capslock = overload(control, esc)
#oneshot has to appear before tab for some reason
meta = oneshot(meta)
tab = overload(meta, tab)
rightcontrol = toggle(symbols)
[symbols]
a=~

