[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
rightshift = overload(alt,?)
capslock = overload(control, esc)
#oneshot has to appear before tab for some reason
tab = overload(meta, tab)

j+k = $
rightcontrol = toggle(cords)

[symbols]
a=~

